kind: pipeline
type: docker
name: build and publish

steps:
  - name: build and publish latest
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - '${DRONE_COMMIT}'
      repo: gonzague/spendspendspent

trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
type: docker
name: build

steps:
  - name: build and publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - '${DRONE_COMMIT}'
      repo: gonzague/spendspendspent

trigger:
  branch:
    exclude:
      - master
  event:
    - push

