kind: pipeline
type: exec
name: Mobile apps yo

platform:
  os: darwin
  arch: amd64

steps:
  - name: flutter test
    environment:
      KEYCHAIN_PASS:
        from_secrets: keychain_pass
    commands:
      - source /Users/gz/.zshrc
      - flutter doctor
      - cd src/main/app
      - ls
      - security unlock-keychain -p ${KEYCHAIN_PASS}
      - ./build-ios.sh

trigger:
  event:
    - push
    - tag
---
kind: pipeline
type: docker
name: Backend & web

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./m2
        - ./src/main/web/node_modules

  - name: build web
    image: cirrusci/flutter:stable
    commands:
      - id
      - cd src/main/app
      - flutter pub get
      - flutter build web --no-sound-null-safety --release
      - cp -R build/web ../resources/public

  ## setting maven version if it's a new release
  - name: set version
    image: maven:3.8-openjdk-17
    commands:
      - mvn versions:set -DnewVersion=${DRONE_TAG} -Dmaven.repo.local=./m2
      - mvn versions:commit -Dmaven.repo.local=./m2
    when:
      event: tag

  - name: build backend
    image: maven:3.8-openjdk-17
    commands:
      - mvn clean install -Dmaven.repo.local=./m2

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./m2
        - ./src/main/web/node_modules


  - name: publish new version
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - '${DRONE_COMMIT}'
        - '${DRONE_TAG}'
        - latest
      repo: gonzague/spendspentspent
      context: ./
      dockerfile: docker/Dockerfile.lite
    when:
      event: tag

  - name: publish commit
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - '${DRONE_COMMIT}'
      repo: gonzague/spendspentspent
      context: ./
      dockerfile: docker/Dockerfile.lite
    when:
      event:
        exclude:
          - tag


  - name: git hub release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: target/SpendSpentSpent-*.jar
    when:
      event: tag
trigger:
  event:
    - push
    - tag

volumes:
  - name: cache
    host:
      path: /home/core/cache
